[package]
name = "voyager-browser"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12", features = ["json", "rustls-tls"] }
tokio = { version = "1.0", features = ["full"] }
kuchiki = "0.8"

# UI
ratatui = "0.26"
crossterm = "0.27"

url = "2.5" # 相対パスを絶対パスに直すために追加
